### ISSUE TITLE
Crash on Android Q (API 29)

### ISSUE THREAD

**Issue by salmankhalid876** [SIARAY/TelephonyManagerPlus#2]
It is crashing on Android Q by giving reason:
Caused by: java.lang.SecurityException: getIccSerialNumber: The user 10134 does not meet the requirements to access device identifiers.
I think it is crashing because getting imei numbers on Android Q is restricted.

**Comment by SIARAY** [comment]
Thank you for your report. I check it.

**Comment by SIARAY** [comment]
> It is crashing on Android Q by giving reason:
> Caused by: java.lang.SecurityException: getIccSerialNumber: The user 10134 does not meet the requirements to access device identifiers.
> I think it is crashing because getting imei numbers on Android Q is restricted.

Thank you for your report. I check it.

**Comment by SIARAY** [comment]
> restricted

It's true. In Android Q, access to imei, ... . is restricted. In the new version (1.0.5), the crashing is prevented.
